# Default setting
name:         "Stacks"
slogan:       "Simple and intuitive website boilerplate"
description:  "Simple and intuitive website boilerplate"
url:          "http://redfrost.com/Stacks/"
markdown:     rdiscount
pygments:     true
sass:
  syntax: scss # scss|sass
  style:  expanded # nested|expanded|compact|compressed	


# Meta
author:       "Redrost"
designer:     "Redrost Design"
designerURL:  "http://redfrost.com/"
copyright:    "Redfrost Design"
FBAppID:      ""
keywords:     "Sexyback"
versionInfo:  "1.5.0"


# Site setting
responsive:   "yes"   # yes|no
siteWidth:    "1170"
navTopFix:    "yes"
logoType:     "text"  # text|image
mobileApp:	  "no"
mobileZoom:   "1.0"   # 1.0=disable zoom
preLoader:	  "no"
siteIndexing: "no"
styleTest:    "no"


## User setting
userInfo:
  businessName: "Opera house"
  userAddress:  "Bennelong Point Sydney NSW 2000 Australia"
  poBox:        "Royal Exchange Sydney"
  phone:        "123-456-7890"
  fax:          "123-456-7890"
  userEmail:    "info@redfrost.com"
  workingHours:	"Working hours: 9:00AM - 5:00PM (Monday to Friday)" 


# Links
snsLink:
  link1:   "#" # Facebook
  link2:   "#" # Twitter
  link3:   "#" # Google+
  link4:   "#" # Youtube
  link5:   "#" # LinkedIn 


# Add-on
typekitID:    ""
formLink:     ""
formID:       "" # wufoo form ID
disqus:       "" # disqus ID
trackingID:   "" # Google analytics ID
videoLink:    "http://player.vimeo.com/video/56860648"


# Footer Note
footerNote:   "<b>IMPORTANT:</b> All works of art within this web site are protected under copyright laws and international conventions. No portion of the artists works or statements may be used, downloaded, reproduced using any means, copied, linked to, or transferred electronically, without prior written permission from the artist."
