# CONFIG - Refresh terminal command after updating this file to apply
testMode:     "off"          # on|off: Display testing helpers


# Default setting
name:         "Stacks"
slogan:       "1P site theme"
description:  "Simple and intuitive website boilerplate"
url:          ""                       # http://yourdomain.com/
permalink:    "date"                   # date|pretty  *Pretty moves all pages inside folders
sass:
  sass_dir:   assets/css/              # path
  syntax:     scss                     # scss|sass
  style:      expanded              # nested|expanded|compact|compressed


# Meta
siteAuthor:   "Redfrost"               # Site owner
designer:     "Redfrost"               # Designer / Developer name
designerURL:  "http://redfrost.com/"   # Designer / Developer website
copyright:    "Redmund Frost D&D"      # Copyright holder
keywords:     "generator"              # for SEO
version:      "v1.0"                   # Dev version
FacebookAppID: ""                      # Facebook App ID


# Layout
layout:       "responsive"  # static|responsive: (for mobile view only. Desktop view is always responsive.)
mobileZoom:   ""            # 1.0=disable zoom, or leave it blank to allow zoom
topNavbar:    "on"          # on|off: top fixed nav
logoType:     "text"        # text|image
gridClass:
  main:       "col-sm-8"
  sidebar:    "col-sm-4"


# User info
userInfo:
  businessName: "Opera house"
  address:      "Bennelong Point Sydney NSW 2000 Australia"
  pobox:        "Royal Exchange Sydney"
  phone:        "123-456-7890"
  fax:          "123-456-7890"
  email:        "info@redfrost.com"
  workingHours:	"Working hours: 9:00AM - 5:00PM (Monday to Friday)"


# Links
snsLink:
  facebook:   "#"    # Facebook
  twitter:    "#"    # Twitter
  tumblr:     "#"    # Tumblr
  googleplus: "#"    # Google+
  instagram:  "#"    # Instagram
  youtube:    "#"    # Youtube
  github:     "#"    # Github
  love:       "#"    # Wherever


# Add-on
lightBox:     "on"   #on|off: Popup
typekitID:    ""     # Typekit ID
formLink:     ""     # Wufoo form Link
formID:       ""     # Wufoo form ID
disqus:       ""     # Disqus ID
trackingID:   "#"    # Google analytics ID
videoLink:    "http://player.vimeo.com/video/56860648"


# Footer Note
footerNote:   "<b>IMPORTANT:</b> All works of art within this web site are protected under copyright laws and international conventions. No portion of the artists works or statements may be used, downloaded, reproduced using any means, copied, linked to, or transferred electronically, without prior written permission from the artist."

